# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: zbar 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "zbar"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Will Glynn"]
  s.date = "2017-11-05"
  s.description = "Ruby bindings for ZBar, a barcode recognition library. Uses FFI to interact with the underlying C library, but has no other dependencies."
  s.email = "will@willglynn.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/zbar.rb",
    "lib/zbar/image.rb",
    "lib/zbar/jpeg.rb",
    "lib/zbar/lib.rb",
    "lib/zbar/library_version.rb",
    "lib/zbar/processor.rb",
    "lib/zbar/symbol.rb",
    "spec/spec_helper.rb",
    "spec/support/file_helpers.rb",
    "spec/support/test.jpg",
    "spec/support/test.pgm",
    "spec/zbar/image_spec.rb",
    "spec/zbar/jpeg_spec.rb",
    "spec/zbar/library_version_spec.rb",
    "spec/zbar/processor_spec.rb",
    "spec/zbar_spec.rb",
    "zbar.gemspec"
  ]
  s.homepage = "http://github.com/willglynn/ruby-zbar"
  s.post_install_message = "\nzbar: This gem depends on the \"zbar\" C library.\n      If it's not installed, `require \"zbar\"` will fail.\n\n"
  s.rubygems_version = "2.4.8"
  s.summary = "Ruby bindings for ZBar, a barcode recognition library"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.7"])
      s.add_development_dependency(%q<rspec-its>, ["~> 1.2"])
      s.add_development_dependency(%q<rdoc>, ["~> 5.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.16"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.1"])
      s.add_development_dependency(%q<rake>, ["~> 12.2"])
    else
      s.add_dependency(%q<ffi>, ["~> 1.0"])
      s.add_dependency(%q<rspec>, ["~> 3.7"])
      s.add_dependency(%q<rspec-its>, ["~> 1.2"])
      s.add_dependency(%q<rdoc>, ["~> 5.1"])
      s.add_dependency(%q<bundler>, ["~> 1.16"])
      s.add_dependency(%q<jeweler>, ["~> 2.1"])
      s.add_dependency(%q<rake>, ["~> 12.2"])
    end
  else
    s.add_dependency(%q<ffi>, ["~> 1.0"])
    s.add_dependency(%q<rspec>, ["~> 3.7"])
    s.add_dependency(%q<rspec-its>, ["~> 1.2"])
    s.add_dependency(%q<rdoc>, ["~> 5.1"])
    s.add_dependency(%q<bundler>, ["~> 1.16"])
    s.add_dependency(%q<jeweler>, ["~> 2.1"])
    s.add_dependency(%q<rake>, ["~> 12.2"])
  end
end

